

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class LadoUsuarioEntities : DbContext
{
    public LadoUsuarioEntities()
        : base("name=LadoUsuarioEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<admin_Employee> admin_Employee { get; set; }

    public DbSet<admin_Login> admin_Login { get; set; }

    public DbSet<Category> Categories { get; set; }

    public DbSet<Customer> Customers { get; set; }

    public DbSet<genMainSlider> genMainSliders { get; set; }

    public DbSet<genPromoRight> genPromoRights { get; set; }

    public DbSet<Order> Orders { get; set; }

    public DbSet<OrderDetail> OrderDetails { get; set; }

    public DbSet<Payment> Payments { get; set; }

    public DbSet<PaymentType> PaymentTypes { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<RecentlyView> RecentlyViews { get; set; }

    public DbSet<Review> Reviews { get; set; }

    public DbSet<Role> Roles { get; set; }

    public DbSet<ShippingDetail> ShippingDetails { get; set; }

    public DbSet<SubCategory> SubCategories { get; set; }

    public DbSet<Supplier> Suppliers { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<Wishlist> Wishlists { get; set; }

}

}

