
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public Order()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

    }


    public int OrderID { get; set; }

    public int CustomerID { get; set; }

    public Nullable<int> PaymentID { get; set; }

    public Nullable<int> ShippingID { get; set; }

    public Nullable<int> Discount { get; set; }

    public Nullable<int> Taxes { get; set; }

    public Nullable<int> TotalAmount { get; set; }

    public Nullable<bool> isCompleted { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<bool> DIspatched { get; set; }

    public Nullable<System.DateTime> DispatchedDate { get; set; }

    public Nullable<bool> Shipped { get; set; }

    public Nullable<System.DateTime> ShippingDate { get; set; }

    public Nullable<bool> Deliver { get; set; }

    public Nullable<System.DateTime> DeliveryDate { get; set; }

    public string Notes { get; set; }

    public Nullable<bool> CancelOrder { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual ShippingDetail ShippingDetail { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

}

}
