
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentType
{

    public PaymentType()
    {

        this.Payments = new HashSet<Payment>();

    }


    public int PayTypeID { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }



    public virtual ICollection<Payment> Payments { get; set; }

}

}
