
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Review
{

    public int ReviewID { get; set; }

    public Nullable<int> CustomerID { get; set; }

    public Nullable<int> ProductID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Review1 { get; set; }

    public Nullable<int> Rate { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<bool> isDelete { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }

}

}
