
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Role
{

    public Role()
    {

        this.admin_Login = new HashSet<admin_Login>();

    }


    public int RoleID { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }



    public virtual ICollection<admin_Login> admin_Login { get; set; }

}

}
