
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ShippingDetail
{

    public ShippingDetail()
    {

        this.Orders = new HashSet<Order>();

    }


    public int ShippingID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string Address { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }



    public virtual ICollection<Order> Orders { get; set; }

}

}
