
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubCategory
{

    public SubCategory()
    {

        this.Products = new HashSet<Product>();

    }


    public int SubCategoryID { get; set; }

    public int CategoryID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Picture1 { get; set; }

    public string Picture2 { get; set; }

    public Nullable<bool> isActive { get; set; }



    public virtual Category Category { get; set; }

    public virtual ICollection<Product> Products { get; set; }

}

}
