
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LadoUsuario.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Wishlist
{

    public int WishlistID { get; set; }

    public int CustomerID { get; set; }

    public int ProductID { get; set; }

    public Nullable<bool> isActive { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }

}

}
